# Generated by Django 4.1 on 2023-01-31 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dnit_bi', '0029_alter_estudo_tecnico_situacao_alter_faixa_sentido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=10)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnit_bi.ticket_freshdesk')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio_paralisado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('paralicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnit_bi.paralisado')),
            ],
        ),
    ]
