# Generated by Django 4.1 on 2022-08-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnit_bi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agente',
            name='celular',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='prioridade',
            field=models.CharField(choices=[('Urgente', 'Urgente'), ('Media', 'Media'), ('Baixa', 'Baixa'), ('Alta', 'Alta')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('Ajuste de Display', 'Ajuste de Display'), ('Falha de Camera', 'Falha de Camera'), ('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical'), ('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando'), ('Falha de disco', 'Falha de disco'), ('Enquadramento', 'Enquadramento'), ('Ajuste de Imagem', 'Ajuste de Imagem'), ('Internet', 'Internet'), ('Equipamento Offline', 'Equipamento Offline'), ('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização'), ('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico'), ('Aferição', 'Aferição'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Conectorização', 'Conectorização'), ('Equipamento sem energia', 'Equipamento sem energia'), ('Ajuste Fino', 'Ajuste Fino'), ('Outro', 'Outro'), ('Poda / Roçada', 'Poda / Roçada'), ('Solicitação de Análise', 'Solicitação de Análise'), ('Iluminador', 'Iluminador'), ('Falha de infração', 'Falha de infração'), ('OCR', 'OCR'), ('Manutenção Preventiva', 'Manutenção Preventiva'), ('Manutenção corretiva', 'Manutenção corretiva'), ('infraestrutura', 'infraestrutura')], max_length=100, null=True),
        ),
    ]
