# Generated by Django 4.1 on 2022-09-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnit_bi', '0002_rename_br_equipamento_br_rename_km_equipamento_km_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='BR',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='KM',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='UL',
        ),
        migrations.AlterField(
            model_name='faixa',
            name='sentido',
            field=models.CharField(choices=[('D', 'DECRESCENTE'), ('C', 'CRESCENTE')], max_length=11),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='prioridade',
            field=models.CharField(choices=[('Media', 'Media'), ('Alta', 'Alta'), ('Urgente', 'Urgente'), ('Baixa', 'Baixa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando'), ('Internet', 'Internet'), ('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('Ajuste de Display', 'Ajuste de Display'), ('Aferição', 'Aferição'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical'), ('Conectorização', 'Conectorização'), ('infraestrutura', 'infraestrutura'), ('Equipamento Offline', 'Equipamento Offline'), ('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('Outro', 'Outro'), ('Iluminador', 'Iluminador'), ('Poda / Roçada', 'Poda / Roçada'), ('OCR', 'OCR'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('Manutenção corretiva', 'Manutenção corretiva'), ('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico'), ('Solicitação de Análise', 'Solicitação de Análise'), ('Manutenção Preventiva', 'Manutenção Preventiva'), ('Falha de Camera', 'Falha de Camera'), ('Equipamento sem energia', 'Equipamento sem energia'), ('Ajuste Fino', 'Ajuste Fino'), ('Falha de disco', 'Falha de disco'), ('Falha de infração', 'Falha de infração'), ('Ajuste de Imagem', 'Ajuste de Imagem'), ('Enquadramento', 'Enquadramento'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='br',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipamento',
            name='km',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipamento',
            name='ul',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
