# Generated by Django 4.1 on 2022-09-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnit_bi', '0003_remove_equipamento_br_remove_equipamento_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='prioridade',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Baixa', 'Baixa'), ('Urgente', 'Urgente'), ('Media', 'Media')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('Iluminador', 'Iluminador'), ('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando'), ('Equipamento Offline', 'Equipamento Offline'), ('Falha de disco', 'Falha de disco'), ('Ajuste Fino', 'Ajuste Fino'), ('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('infraestrutura', 'infraestrutura'), ('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico'), ('Manutenção Preventiva', 'Manutenção Preventiva'), ('OCR', 'OCR'), ('Outro', 'Outro'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização'), ('Poda / Roçada', 'Poda / Roçada'), ('Ajuste de Display', 'Ajuste de Display'), ('Falha de Camera', 'Falha de Camera'), ('Equipamento sem energia', 'Equipamento sem energia'), ('Aferição', 'Aferição'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Falha de infração', 'Falha de infração'), ('Internet', 'Internet'), ('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical'), ('Solicitação de Análise', 'Solicitação de Análise'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('Conectorização', 'Conectorização'), ('Manutenção corretiva', 'Manutenção corretiva'), ('Enquadramento', 'Enquadramento'), ('Ajuste de Imagem', 'Ajuste de Imagem')], max_length=100, null=True),
        ),
    ]
