# Generated by Django 4.1 on 2022-09-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnit_bi', '0004_alter_ticket_freshdesk_prioridade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faixa',
            name='sentido',
            field=models.CharField(choices=[('C', 'CRESCENTE'), ('D', 'DECRESCENTE')], max_length=11),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='prioridade',
            field=models.CharField(choices=[('Media', 'Media'), ('Urgente', 'Urgente'), ('Alta', 'Alta'), ('Baixa', 'Baixa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('Equipamento Offline', 'Equipamento Offline'), ('Solicitação de Análise', 'Solicitação de Análise'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical'), ('Falha de infração', 'Falha de infração'), ('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando'), ('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('Ajuste de Display', 'Ajuste de Display'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('Manutenção corretiva', 'Manutenção corretiva'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização'), ('Equipamento sem energia', 'Equipamento sem energia'), ('Conectorização', 'Conectorização'), ('Poda / Roçada', 'Poda / Roçada'), ('Ajuste Fino', 'Ajuste Fino'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Ajuste de Imagem', 'Ajuste de Imagem'), ('Enquadramento', 'Enquadramento'), ('Iluminador', 'Iluminador'), ('Falha de Camera', 'Falha de Camera'), ('Aferição', 'Aferição'), ('infraestrutura', 'infraestrutura'), ('Manutenção Preventiva', 'Manutenção Preventiva'), ('Internet', 'Internet'), ('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico'), ('Falha de disco', 'Falha de disco'), ('Outro', 'Outro'), ('OCR', 'OCR')], max_length=100, null=True),
        ),
    ]
