# Generated by Django 4.1 on 2022-09-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnit_bi', '0005_alter_faixa_sentido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faixa',
            name='sentido',
            field=models.CharField(choices=[('D', 'DECRESCENTE'), ('C', 'CRESCENTE')], max_length=11),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='prioridade',
            field=models.CharField(choices=[('Urgente', 'Urgente'), ('Baixa', 'Baixa'), ('Alta', 'Alta'), ('Media', 'Media')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('Outro', 'Outro'), ('Manutenção Preventiva', 'Manutenção Preventiva'), ('Manutenção corretiva', 'Manutenção corretiva'), ('Falha de disco', 'Falha de disco'), ('Ajuste de Imagem', 'Ajuste de Imagem'), ('Ajuste Fino', 'Ajuste Fino'), ('Poda / Roçada', 'Poda / Roçada'), ('Falha de Camera', 'Falha de Camera'), ('OCR', 'OCR'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical'), ('Solicitação de Análise', 'Solicitação de Análise'), ('infraestrutura', 'infraestrutura'), ('Aferição', 'Aferição'), ('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico'), ('Iluminador', 'Iluminador'), ('Conectorização', 'Conectorização'), ('Enquadramento', 'Enquadramento'), ('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('Equipamento Offline', 'Equipamento Offline'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização'), ('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('Internet', 'Internet'), ('Falha de infração', 'Falha de infração'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Equipamento sem energia', 'Equipamento sem energia'), ('Ajuste de Display', 'Ajuste de Display'), ('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando')], max_length=100, null=True),
        ),
    ]
