# Generated by Django 4.1 on 2022-09-01 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnit_bi', '0006_alter_faixa_sentido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='prioridade',
            field=models.CharField(choices=[('Media', 'Media'), ('Urgente', 'Urgente'), ('Alta', 'Alta'), ('Baixa', 'Baixa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('Ajuste de Display', 'Ajuste de Display'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização'), ('Ajuste Fino', 'Ajuste Fino'), ('Enquadramento', 'Enquadramento'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical'), ('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Falha de Camera', 'Falha de Camera'), ('Ajuste de Imagem', 'Ajuste de Imagem'), ('Equipamento Offline', 'Equipamento Offline'), ('infraestrutura', 'infraestrutura'), ('Falha de infração', 'Falha de infração'), ('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico'), ('Manutenção corretiva', 'Manutenção corretiva'), ('Solicitação de Análise', 'Solicitação de Análise'), ('Poda / Roçada', 'Poda / Roçada'), ('Conectorização', 'Conectorização'), ('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('Outro', 'Outro'), ('Equipamento sem energia', 'Equipamento sem energia'), ('Manutenção Preventiva', 'Manutenção Preventiva'), ('Falha de disco', 'Falha de disco'), ('Aferição', 'Aferição'), ('OCR', 'OCR'), ('Internet', 'Internet'), ('Iluminador', 'Iluminador')], max_length=100, null=True),
        ),
    ]
