# Generated by Django 4.1 on 2022-09-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnit_bi', '0008_alter_faixa_sentido_alter_ticket_freshdesk_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='prioridade',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Urgente', 'Urgente'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('Solicitação de Análise', 'Solicitação de Análise'), ('OCR', 'OCR'), ('Equipamento sem energia', 'Equipamento sem energia'), ('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico'), ('Falha de Camera', 'Falha de Camera'), ('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando'), ('Ajuste de Display', 'Ajuste de Display'), ('Ajuste de Imagem', 'Ajuste de Imagem'), ('infraestrutura', 'infraestrutura'), ('Manutenção Preventiva', 'Manutenção Preventiva'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical'), ('Internet', 'Internet'), ('Ajuste Fino', 'Ajuste Fino'), ('Outro', 'Outro'), ('Poda / Roçada', 'Poda / Roçada'), ('Conectorização', 'Conectorização'), ('Iluminador', 'Iluminador'), ('Aferição', 'Aferição'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Manutenção corretiva', 'Manutenção corretiva'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização'), ('Enquadramento', 'Enquadramento'), ('Falha de infração', 'Falha de infração'), ('Falha de disco', 'Falha de disco'), ('Equipamento Offline', 'Equipamento Offline')], max_length=100, null=True),
        ),
    ]
