# Generated by Django 4.1 on 2022-09-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnit_bi', '0010_alter_faixa_sentido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faixa',
            name='sentido',
            field=models.CharField(choices=[('C', 'CRESCENTE'), ('D', 'DECRESCENTE')], max_length=11),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='prioridade',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Urgente', 'Urgente'), ('Media', 'Media'), ('Baixa', 'Baixa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('Enquadramento', 'Enquadramento'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('Manutenção corretiva', 'Manutenção corretiva'), ('Aferição', 'Aferição'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Equipamento Offline', 'Equipamento Offline'), ('Internet', 'Internet'), ('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando'), ('OCR', 'OCR'), ('Ajuste de Display', 'Ajuste de Display'), ('Ajuste Fino', 'Ajuste Fino'), ('Falha de disco', 'Falha de disco'), ('Outro', 'Outro'), ('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico'), ('Iluminador', 'Iluminador'), ('Manutenção Preventiva', 'Manutenção Preventiva'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização'), ('Ajuste de Imagem', 'Ajuste de Imagem'), ('Equipamento sem energia', 'Equipamento sem energia'), ('Poda / Roçada', 'Poda / Roçada'), ('Falha de Camera', 'Falha de Camera'), ('Conectorização', 'Conectorização'), ('Falha de infração', 'Falha de infração'), ('infraestrutura', 'infraestrutura'), ('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('Solicitação de Análise', 'Solicitação de Análise'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical')], max_length=100, null=True),
        ),
    ]
