# Generated by Django 4.1 on 2022-09-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnit_bi', '0012_alter_ticket_freshdesk_prioridade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agente',
            name='grupo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='agente',
            name='grupo_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='prioridade',
            field=models.CharField(choices=[('Media', 'Media'), ('Urgente', 'Urgente'), ('Baixa', 'Baixa'), ('Alta', 'Alta')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('Iluminador', 'Iluminador'), ('Manutenção Preventiva', 'Manutenção Preventiva'), ('Poda / Roçada', 'Poda / Roçada'), ('Service Task', 'Service Task'), ('Solicitação de Análise', 'Solicitação de Análise'), ('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando'), ('Ajuste Fino', 'Ajuste Fino'), ('Falha de Camera', 'Falha de Camera'), ('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('infraestrutura', 'infraestrutura'), ('Equipamento Offline', 'Equipamento Offline'), ('Ajuste de Imagem', 'Ajuste de Imagem'), ('Falha de infração', 'Falha de infração'), ('Falha de disco', 'Falha de disco'), ('Equipamento sem energia', 'Equipamento sem energia'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('Conectorização', 'Conectorização'), ('Outro', 'Outro'), ('Ajuste de Display', 'Ajuste de Display'), ('Internet', 'Internet'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('Manutenção corretiva', 'Manutenção corretiva'), ('Enquadramento', 'Enquadramento'), ('OCR', 'OCR'), ('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical'), ('Aferição', 'Aferição'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização')], max_length=100, null=True),
        ),
    ]
