# Generated by Django 4.1 on 2022-09-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnit_bi', '0015_alter_faixa_sentido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='porta_velsis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='prioridade',
            field=models.CharField(choices=[('Urgente', 'Urgente'), ('Media', 'Media'), ('Alta', 'Alta'), ('Baixa', 'Baixa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando'), ('Service Task', 'Service Task'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('Falha de Camera', 'Falha de Camera'), ('Aferição', 'Aferição'), ('infraestrutura', 'infraestrutura'), ('Enquadramento', 'Enquadramento'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização'), ('Falha de infração', 'Falha de infração'), ('Equipamento sem energia', 'Equipamento sem energia'), ('Ajuste Fino', 'Ajuste Fino'), ('OCR', 'OCR'), ('Ajuste de Display', 'Ajuste de Display'), ('Manutenção Preventiva', 'Manutenção Preventiva'), ('Outro', 'Outro'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical'), ('Solicitação de Análise', 'Solicitação de Análise'), ('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('Internet', 'Internet'), ('Manutenção corretiva', 'Manutenção corretiva'), ('Iluminador', 'Iluminador'), ('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico'), ('Equipamento Offline', 'Equipamento Offline'), ('Poda / Roçada', 'Poda / Roçada'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('Conectorização', 'Conectorização'), ('Ajuste de Imagem', 'Ajuste de Imagem'), ('Falha de disco', 'Falha de disco')], max_length=100, null=True),
        ),
    ]
