# Generated by Django 4.1 on 2022-10-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnit_bi', '0016_equipamento_porta_velsis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paralisado',
            name='situacao',
            field=models.CharField(choices=[('Em ação', 'Em ação'), ('Pista danificada', 'Pista danificada'), ('Aguardando liberação DNIT', 'Aguardando liberação DNIT'), ('Desparalisação Solicitada', 'Desparalisação Solicitada')], default='Em ação', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='prioridade',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Baixa', 'Baixa'), ('Urgente', 'Urgente'), ('Media', 'Media')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('Iluminador', 'Iluminador'), ('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('Falha de infração', 'Falha de infração'), ('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando'), ('Manutenção Preventiva', 'Manutenção Preventiva'), ('Ajuste Fino', 'Ajuste Fino'), ('Outro', 'Outro'), ('OCR', 'OCR'), ('Equipamento sem energia', 'Equipamento sem energia'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical'), ('Falha de disco', 'Falha de disco'), ('Service Task', 'Service Task'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Manutenção corretiva', 'Manutenção corretiva'), ('infraestrutura', 'infraestrutura'), ('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico'), ('Equipamento Offline', 'Equipamento Offline'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('Ajuste de Imagem', 'Ajuste de Imagem'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização'), ('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('Falha de Camera', 'Falha de Camera'), ('Poda / Roçada', 'Poda / Roçada'), ('Solicitação de Análise', 'Solicitação de Análise'), ('Enquadramento', 'Enquadramento'), ('Internet', 'Internet'), ('Ajuste de Display', 'Ajuste de Display'), ('Aferição', 'Aferição'), ('Conectorização', 'Conectorização')], max_length=100, null=True),
        ),
    ]
