# Generated by Django 4.1 on 2022-10-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dnit_bi', '0018_remove_equipamento_codigo_estudo_tecnico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudo_tecnico',
            name='Equipamento',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='et',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dnit_bi.estudo_tecnico'),
        ),
        migrations.AddField(
            model_name='estudo_tecnico',
            name='br',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudo_tecnico',
            name='km',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudo_tecnico',
            name='municipio',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dnit_bi.municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudo_tecnico',
            name='tipo_equipamento',
            field=models.CharField(default=0, max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudo_tecnico',
            name='situacao',
            field=models.CharField(choices=[('Aguardando Análise', 'Aguardando Análise'), ('Aguardando Ajuste Elaboração', 'Aguardando Ajuste Elaboração'), ('Em Análise', 'Em Análise'), ('Em Elaboração', 'Em Elaboração'), ('Aguardando Revisão Análise', 'Aguardando Revisão Análise'), ('Aprovado', 'Aprovado'), ('Anulado', 'Anulado'), ('Aguardando Elaboração', 'Aguardando Elaboração')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='prioridade',
            field=models.CharField(choices=[('Urgente', 'Urgente'), ('Baixa', 'Baixa'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('Service Task', 'Service Task'), ('Enquadramento', 'Enquadramento'), ('Aferição', 'Aferição'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização'), ('Outro', 'Outro'), ('Ajuste Fino', 'Ajuste Fino'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Poda / Roçada', 'Poda / Roçada'), ('Iluminador', 'Iluminador'), ('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('Falha de disco', 'Falha de disco'), ('Ajuste de Imagem', 'Ajuste de Imagem'), ('Manutenção Preventiva', 'Manutenção Preventiva'), ('Ajuste de Display', 'Ajuste de Display'), ('OCR', 'OCR'), ('Manutenção corretiva', 'Manutenção corretiva'), ('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando'), ('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('Internet', 'Internet'), ('Falha de Camera', 'Falha de Camera'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical'), ('infraestrutura', 'infraestrutura'), ('Conectorização', 'Conectorização'), ('Equipamento sem energia', 'Equipamento sem energia'), ('Falha de infração', 'Falha de infração'), ('Solicitação de Análise', 'Solicitação de Análise'), ('Equipamento Offline', 'Equipamento Offline'), ('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico')], max_length=100, null=True),
        ),
    ]
