# Generated by Django 4.1 on 2022-10-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnit_bi', '0020_alter_estudo_tecnico_situacao_alter_municipio_lote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudo_tecnico',
            name='situacao',
            field=models.CharField(choices=[('Aprovado', 'Aprovado'), ('Aguardando Elaboração', 'Aguardando Elaboração'), ('Anulado', 'Anulado'), ('Em Elaboração', 'Em Elaboração'), ('Aguardando Revisão Análise', 'Aguardando Revisão Análise'), ('Aguardando Ajuste Elaboração', 'Aguardando Ajuste Elaboração'), ('Em Análise', 'Em Análise'), ('Aguardando Análise', 'Aguardando Análise')], max_length=40),
        ),
        migrations.AlterField(
            model_name='estudo_tecnico',
            name='tipo_equipamento',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='prioridade',
            field=models.CharField(choices=[('Baixa', 'Baixa'), ('Urgente', 'Urgente'), ('Alta', 'Alta'), ('Media', 'Media')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico'), ('Poda / Roçada', 'Poda / Roçada'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical'), ('Enquadramento', 'Enquadramento'), ('Equipamento sem energia', 'Equipamento sem energia'), ('Outro', 'Outro'), ('infraestrutura', 'infraestrutura'), ('Ajuste de Imagem', 'Ajuste de Imagem'), ('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('Ajuste de Display', 'Ajuste de Display'), ('Solicitação de Análise', 'Solicitação de Análise'), ('Equipamento Offline', 'Equipamento Offline'), ('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando'), ('Falha de Camera', 'Falha de Camera'), ('Manutenção corretiva', 'Manutenção corretiva'), ('Aferição', 'Aferição'), ('Falha de infração', 'Falha de infração'), ('Service Task', 'Service Task'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Conectorização', 'Conectorização'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('Manutenção Preventiva', 'Manutenção Preventiva'), ('Ajuste Fino', 'Ajuste Fino'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização'), ('Falha de disco', 'Falha de disco'), ('Internet', 'Internet'), ('Iluminador', 'Iluminador'), ('OCR', 'OCR')], max_length=100, null=True),
        ),
    ]
