# Generated by Django 4.1 on 2022-10-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnit_bi', '0021_alter_estudo_tecnico_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudo_tecnico',
            name='situacao',
            field=models.CharField(choices=[('Em Elaboração', 'Em Elaboração'), ('Aguardando Ajuste Elaboração', 'Aguardando Ajuste Elaboração'), ('Aguardando Revisão Análise', 'Aguardando Revisão Análise'), ('Anulado', 'Anulado'), ('Em Análise', 'Em Análise'), ('Aguardando Elaboração', 'Aguardando Elaboração'), ('Aguardando Análise', 'Aguardando Análise'), ('Aprovado', 'Aprovado')], max_length=40),
        ),
        migrations.AlterField(
            model_name='estudo_tecnico',
            name='tipo_equipamento',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='prioridade',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Urgente', 'Urgente'), ('Media', 'Media'), ('Baixa', 'Baixa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('Poda / Roçada', 'Poda / Roçada'), ('Falha de infração', 'Falha de infração'), ('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('Aferição', 'Aferição'), ('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('Manutenção corretiva', 'Manutenção corretiva'), ('OCR', 'OCR'), ('Service Task', 'Service Task'), ('infraestrutura', 'infraestrutura'), ('Iluminador', 'Iluminador'), ('Falha de disco', 'Falha de disco'), ('Internet', 'Internet'), ('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico'), ('Enquadramento', 'Enquadramento'), ('Falha de Camera', 'Falha de Camera'), ('Manutenção Preventiva', 'Manutenção Preventiva'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical'), ('Outro', 'Outro'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização'), ('Equipamento sem energia', 'Equipamento sem energia'), ('Solicitação de Análise', 'Solicitação de Análise'), ('Equipamento Offline', 'Equipamento Offline'), ('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando'), ('Ajuste de Imagem', 'Ajuste de Imagem'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Conectorização', 'Conectorização'), ('Ajuste de Display', 'Ajuste de Display'), ('Ajuste Fino', 'Ajuste Fino')], max_length=100, null=True),
        ),
    ]
