# Generated by Django 4.1 on 2022-10-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnit_bi', '0022_alter_estudo_tecnico_situacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudo_tecnico',
            name='faixas',
            field=models.CharField(default=1, max_length=36),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudo_tecnico',
            name='situacao',
            field=models.CharField(choices=[('Aguardando Ajuste Elaboração', 'Aguardando Ajuste Elaboração'), ('Aguardando Análise', 'Aguardando Análise'), ('Em Elaboração', 'Em Elaboração'), ('Em Análise', 'Em Análise'), ('Aguardando Elaboração', 'Aguardando Elaboração'), ('Aprovado', 'Aprovado'), ('Anulado', 'Anulado'), ('Aguardando Revisão Análise', 'Aguardando Revisão Análise')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='prioridade',
            field=models.CharField(choices=[('Media', 'Media'), ('Alta', 'Alta'), ('Urgente', 'Urgente'), ('Baixa', 'Baixa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('Manutenção Preventiva', 'Manutenção Preventiva'), ('Aferição', 'Aferição'), ('Equipamento sem energia', 'Equipamento sem energia'), ('Ajuste Fino', 'Ajuste Fino'), ('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando'), ('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Ajuste de Imagem', 'Ajuste de Imagem'), ('Solicitação de Análise', 'Solicitação de Análise'), ('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical'), ('Poda / Roçada', 'Poda / Roçada'), ('Falha de disco', 'Falha de disco'), ('Internet', 'Internet'), ('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('Enquadramento', 'Enquadramento'), ('Conectorização', 'Conectorização'), ('Outro', 'Outro'), ('Falha de infração', 'Falha de infração'), ('Ajuste de Display', 'Ajuste de Display'), ('Falha de Camera', 'Falha de Camera'), ('Equipamento Offline', 'Equipamento Offline'), ('OCR', 'OCR'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização'), ('Manutenção corretiva', 'Manutenção corretiva'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('Service Task', 'Service Task'), ('Iluminador', 'Iluminador'), ('infraestrutura', 'infraestrutura')], max_length=100, null=True),
        ),
    ]
