# Generated by Django 4.1 on 2022-11-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnit_bi', '0023_estudo_tecnico_faixas_alter_estudo_tecnico_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudo_tecnico',
            name='situacao',
            field=models.CharField(choices=[('Aguardando Ajuste Elaboração', 'Aguardando Ajuste Elaboração'), ('Aprovado', 'Aprovado'), ('Aguardando Revisão Análise', 'Aguardando Revisão Análise'), ('Anulado', 'Anulado'), ('Aguardando Elaboração', 'Aguardando Elaboração'), ('Em Elaboração', 'Em Elaboração'), ('Em Análise', 'Em Análise'), ('Aguardando Análise', 'Aguardando Análise')], max_length=40),
        ),
        migrations.AlterField(
            model_name='paralisado',
            name='situacao',
            field=models.CharField(choices=[('Em ação', 'Em ação'), ('Pista danificada', 'Pista danificada'), ('Aguardando autorização diretoria Fotosensores', 'Aguardando autorização diretoria Fotosensores'), ('Aguardando Aferição/Laudo', 'Aguardando Aferição/Laudo'), ('Desparalisação Solicitada', 'Desparalisação Solicitada')], default='Em ação', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('Iluminador', 'Iluminador'), ('infraestrutura', 'infraestrutura'), ('OCR', 'OCR'), ('Enquadramento', 'Enquadramento'), ('Ajuste de Display', 'Ajuste de Display'), ('Falha de infração', 'Falha de infração'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Aferição', 'Aferição'), ('Manutenção Preventiva', 'Manutenção Preventiva'), ('Falha de Camera', 'Falha de Camera'), ('Outro', 'Outro'), ('Conectorização', 'Conectorização'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical'), ('Ajuste Fino', 'Ajuste Fino'), ('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando'), ('Service Task', 'Service Task'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('Manutenção corretiva', 'Manutenção corretiva'), ('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('Solicitação de Análise', 'Solicitação de Análise'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização'), ('Equipamento Offline', 'Equipamento Offline'), ('Equipamento sem energia', 'Equipamento sem energia'), ('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('Ajuste de Imagem', 'Ajuste de Imagem'), ('Falha de disco', 'Falha de disco'), ('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico'), ('Poda / Roçada', 'Poda / Roçada'), ('Internet', 'Internet')], max_length=100, null=True),
        ),
    ]
