# Generated by Django 4.1 on 2022-11-10 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dnit_bi', '0025_alter_estudo_tecnico_situacao_alter_faixa_sentido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentoanotacoes',
            name='usuario',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudo_tecnico',
            name='situacao',
            field=models.CharField(choices=[('Aguardando Análise', 'Aguardando Análise'), ('Aprovado', 'Aprovado'), ('Aguardando Elaboração', 'Aguardando Elaboração'), ('Aguardando Ajuste Elaboração', 'Aguardando Ajuste Elaboração'), ('Aguardando Revisão Análise', 'Aguardando Revisão Análise'), ('Em Análise', 'Em Análise'), ('Anulado', 'Anulado'), ('Em Elaboração', 'Em Elaboração')], max_length=40),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='prioridade',
            field=models.CharField(choices=[('Media', 'Media'), ('Alta', 'Alta'), ('Baixa', 'Baixa'), ('Urgente', 'Urgente')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('Iluminador', 'Iluminador'), ('Internet', 'Internet'), ('Falha de infração', 'Falha de infração'), ('Ajuste de Display', 'Ajuste de Display'), ('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('Aferição', 'Aferição'), ('Outro', 'Outro'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização'), ('Solicitação de Análise', 'Solicitação de Análise'), ('Equipamento sem energia', 'Equipamento sem energia'), ('Ajuste Fino', 'Ajuste Fino'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical'), ('Service Task', 'Service Task'), ('Conectorização', 'Conectorização'), ('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico'), ('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('Falha de disco', 'Falha de disco'), ('OCR', 'OCR'), ('Enquadramento', 'Enquadramento'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('Poda / Roçada', 'Poda / Roçada'), ('infraestrutura', 'infraestrutura'), ('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando'), ('Falha de Camera', 'Falha de Camera'), ('Ajuste de Imagem', 'Ajuste de Imagem'), ('Equipamento Offline', 'Equipamento Offline'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Manutenção corretiva', 'Manutenção corretiva'), ('Manutenção Preventiva', 'Manutenção Preventiva')], max_length=100, null=True),
        ),
    ]
