# Generated by Django 4.1 on 2023-01-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dnit_bi', '0028_alter_estudo_tecnico_situacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudo_tecnico',
            name='situacao',
            field=models.CharField(choices=[('Aguardando Revisão Análise', 'Aguardando Revisão Análise'), ('Aguardando Análise', 'Aguardando Análise'), ('Aprovado', 'Aprovado'), ('Em Análise', 'Em Análise'), ('Em Elaboração', 'Em Elaboração'), ('Aguardando Ajuste Elaboração', 'Aguardando Ajuste Elaboração'), ('Aguardando Elaboração', 'Aguardando Elaboração'), ('Anulado', 'Anulado')], max_length=40),
        ),
        migrations.AlterField(
            model_name='faixa',
            name='sentido',
            field=models.CharField(choices=[('D', 'DECRESCENTE'), ('C', 'CRESCENTE')], max_length=11),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='prioridade',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Urgente', 'Urgente'), ('Baixa', 'Baixa')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket_freshdesk',
            name='tipo',
            field=models.CharField(choices=[('PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS', 'PISTA DANIFICADA SEM CONDIÇÕES PRA REFAZER LAÇOS'), ('Ajuste de Imagem', 'Ajuste de Imagem'), ('Falha de infração', 'Falha de infração'), ('Instalação / Reparo de cabo lógico', 'Instalação / Reparo de cabo lógico'), ('Implantação/Reparo de sinalização horizontal', 'Implantação/Reparo de sinalização horizontal'), ('Conectorização', 'Conectorização'), ('Manutenção Preventiva', 'Manutenção Preventiva'), ('Implantação / ajuste de sinalização', 'Implantação / ajuste de sinalização'), ('Sem passagem / Não infracionando', 'Sem passagem / Não infracionando'), ('Aferição', 'Aferição'), ('Implantação/Reparo de sinalização vertical', 'Implantação/Reparo de sinalização vertical'), ('Equipamento Offline', 'Equipamento Offline'), ('OCR', 'OCR'), ('Ajuste de Display', 'Ajuste de Display'), ('Outro', 'Outro'), ('Equipamento sem energia', 'Equipamento sem energia'), ('infraestrutura', 'infraestrutura'), ('Ajuste Fino', 'Ajuste Fino'), ('Configuração de envio SIOR', 'Configuração de envio SIOR'), ('Enquadramento', 'Enquadramento'), ('Poda / Roçada', 'Poda / Roçada'), ('Falha de Camera', 'Falha de Camera'), ('Service Task', 'Service Task'), ('Instalação / Reparo de energia eletrica', 'Instalação / Reparo de energia eletrica'), ('Solicitação de Análise', 'Solicitação de Análise'), ('Internet', 'Internet'), ('Iluminador', 'Iluminador'), ('Falha de disco', 'Falha de disco'), ('Manutenção corretiva', 'Manutenção corretiva')], max_length=100, null=True),
        ),
    ]
